version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    restart: always
    env_file:
      - .env
    expose:
      - "3306"
    tty: true
    networks:
      - inception
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "--silent"]
     retries: 20
     timeout: 2s
     interval: 5s

  nginx:
    image: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www
    tty: true
    networks:
      - inception

    
  wordpress:
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www
    tty: true
    networks:
      - inception
volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/DB
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/WordPress
networks:
  inception: